### PR TITLE
Output AbstractVector for vector input

### PR DESCRIPTION
**Pull request by Abhishek-1Bhatt**
Allows compatibility with sensitivity algorithms from DiffEqSensitivity for doing SciML stuff.

### CODE REVIEW

**Comment by chriselrod** [comment]
I think we have a decision to be made here.
I think it is reasonable to internally always require that we have a trailing "batch" dimension.
In that case, vector inputs here should internally be represented by matrices with a `static(1)` for the last axis.

This may be able to simplify internal code.
But, code was mostly written to allow having the batch dimension be missing for evaluating a single subject.
So my initial thought was that you'd look for where the extra batch size dimension was getting tacked on.

Although, as I just said, perhaps it is better to guarantee that we internally always have a trailing batch size.
In which case, we would want to drop the size-1 last axis before returning, if given input that did not have it.

That said, dropping a dimension should not be done by allocating a new vector and copying memory over to it.
Maybe `vec` is reasonable.
We should probably also be a little more disciplined about managing batch dimensions.

**Comment by Abhishek-1Bhatt** [comment]
Yeah vec is clearly better, earlier I was so focused on making the sensitivity algorithm work that I totally glossed over the fact that it will allocate a whole new vector.

```julia
using SimpleChains, BenchmarkTools
sc = SimpleChain(static(4), TurboDense{true}(tanh, 6), TurboDense{true}(tanh, 10))

x = Float32.(rand(4))
p = SimpleChains.init_params(sc)

op = sc(x,p)
```
```julia
julia> @btime vec(op)
  58.087 ns (1 allocation: 16 bytes)
10-element StrideArraysCore.PtrArray{Tuple{Static.StaticInt{10}}, (true,), Float32, 1, 1, 0, (1,), Tuple{Static.StaticInt{4}}, Tuple{Static.StaticInt{1}}} with indices 1:1:10:
  0.23134874
  0.30115283
 -0.5519638
  ⋮
  0.08602831
  0.21340065
  0.15650724

julia> @btime op[1:end]
  189.457 ns (2 allocations: 128 bytes)
10-element Vector{Float32}:
  0.23134874
  0.30115283
 -0.5519638
  ⋮
  0.08602831
  0.21340065
  0.15650724
```

**Comment by Abhishek-1Bhatt** [comment]
But there's one thing with vec that's a little concerning, the training is bumpy. The loss oscillates when vec is used:

```julia
234.97673f0
118.47133f0
110.910095f0
108.85049f0
105.91254f0
103.5022f0
102.089714f0
103.261894f0
164.86229f0
92.939156f0
87.91119f0
86.4812f0
81.68159f0
75.71357f0
77.10669f0
81.97709f0
78.30451f0
75.50763f0
75.33827f0
58.464375f0
64.087105f0
56.56521f0
54.184776f0
53.585068f0
72.51484f0
69.2475f0
74.99938f0
83.6168f0
85.33057f0
75.901306f0
80.179825f0
71.793106f0
72.45498f0
66.434746f0
76.68074f0
77.09675f0
67.36835f0
65.62345f0
59.940178f0
61.46498f0
63.170082f0
65.21767f0
66.909065f0
70.14293f0
67.3382f0
73.09933f0
74.10152f0
76.32311f0
65.89734f0
101.31755f0
121.889275f0
188.5355f0
85.090416f0
81.85719f0
76.84787f0
71.490364f0
65.85338f0
69.42293f0
69.24264f0
65.63481f0
77.30762f0
60.591522f0
60.658295f0
44.15837f0
36.070877f0
32.118755f0
50.66407f0
136.39815f0
50.00641f0
40.61051f0
76.53271f0
87.49839f0
91.53681f0
96.698746f0
72.29137f0
59.46588f0
65.11872f0
66.332985f0
73.143105f0
77.63482f0
71.33233f0
68.78779f0
75.96084f0
81.402985f0
83.97315f0
86.27797f0
88.057755f0
89.27242f0
87.89f0
90.58048f0
86.962524f0
88.81367f0
86.481834f0
83.00058f0
82.19744f0
77.693474f0
76.692955f0
76.28544f0
72.44382f0
67.187004f0
61.072727f0
55.06997f0
51.494083f0
56.06038f0
44.049908f0
44.598637f0
45.17877f0
44.309246f0
44.24995f0
49.531612f0
54.041157f0
42.045444f0
34.953827f0
34.71583f0
32.753292f0
30.38318f0
30.067734f0
33.13373f0
30.628204f0
36.852154f0
27.820122f0
33.860855f0
34.11753f0
26.616024f0
26.20765f0
25.70454f0
30.038736f0
32.217415f0
48.904015f0
26.379679f0
31.50407f0
30.242844f0
32.993343f0
30.45091f0
31.367426f0
37.28815f0
36.802124f0
45.38878f0
31.648138f0
29.933031f0
24.233555f0
27.790548f0
28.33955f0
28.250595f0
37.141293f0
28.139256f0
24.309729f0
24.995043f0
34.289406f0
25.109253f0
26.015919f0
24.62404f0
26.641695f0
22.942158f0
22.943953f0
20.776281f0
20.839815f0
20.518671f0
18.489914f0
14.139467f0
12.995863f0
15.665463f0
17.736067f0
19.359278f0
18.905352f0
16.909716f0
17.026716f0
15.987553f0
13.364039f0
17.292046f0
13.484684f0
9.884144f0
6.9076176f0
5.4944243f0
13.073125f0
9.962681f0
23.771502f0
59.229088f0
55.447586f0
49.338444f0
45.088154f0
45.011417f0
51.40616f0
54.96852f0
56.170788f0
56.673687f0
57.182915f0
53.357464f0
56.163525f0
57.250767f0
62.296436f0
60.72041f0
56.145473f0
58.67447f0
55.200745f0
54.146244f0
56.29122f0
52.337074f0
54.598763f0
43.420757f0
34.217445f0
29.927713f0
27.107933f0
29.118477f0
24.81231f0
14.936499f0
14.846491f0
15.468025f0
15.798425f0
17.506603f0
15.720645f0
14.389747f0
15.517727f0
15.89789f0
18.970592f0
16.100029f0
19.72131f0
17.220396f0
13.276166f0
13.239117f0
12.475818f0
12.033122f0
12.92985f0
11.085583f0
8.29182f0
13.181355f0
19.769156f0
15.350469f0
12.702631f0
20.936714f0
19.581762f0
10.977915f0
8.697313f0
15.890189f0
13.537543f0
8.695144f0
8.440544f0
11.449639f0
9.717319f0
7.763929f0
8.044106f0
8.900388f0
7.6771884f0
7.334781f0
26.42822f0
5.180854f0
19.701231f0
12.614942f0
6.3437576f0
8.020753f0
6.6628585f0
15.796483f0
5.498042f0
5.411326f0
5.361319f0
4.7880244f0
5.3085604f0
5.1671243f0
4.5032663f0
5.0528364f0
4.371953f0
5.286566f0
5.003929f0
7.074936f0
4.2753005f0
5.223147f0
4.4560137f0
4.8212833f0
4.844404f0
4.350565f0
4.0154624f0
4.6782737f0
4.692592f0
4.6906276f0
4.130772f0
4.4382563f0
5.0569243f0
4.298064f0
4.226475f0
5.1627064f0
5.646669f0
3.9995637f0
4.690556f0
3.8512537f0
5.1658344f0
4.4094872f0
5.320953f0
3.8936937f0
3.6396465f0
4.1501064f0
4.29053f0
4.373843f0
4.556334f0
4.491953f0
4.6922483f0
4.2587852f0
4.728472f0
3.8725543f0
3.398667f0
3.7890706f0
3.398667f0
u: 250-element Vector{Float32}:
 -0.48171264
  0.6257474
  0.69599664
  ⋮
 -1.8141717
 -0.6986019
  0.6414147
```
vs when indexing

```julia
218.38708f0
116.63474f0
109.16026f0
107.74801f0
104.388016f0
101.2846f0
97.34865f0
94.72384f0
93.1462f0
91.78705f0
90.74295f0
89.46916f0
87.65039f0
85.4402f0
82.99031f0
80.28091f0
77.27717f0
74.02795f0
70.53014f0
66.57503f0
61.55132f0
55.13723f0
47.50684f0
34.769836f0
37.054413f0
45.200535f0
45.694126f0
40.452827f0
32.0877f0
27.667635f0
34.250908f0
31.534317f0
25.169405f0
21.776632f0
19.514738f0
16.853125f0
25.36427f0
15.558331f0
19.08537f0
20.821991f0
17.539713f0
12.801387f0
15.645041f0
13.336873f0
10.066191f0
10.121152f0
10.155362f0
9.2631035f0
8.16555f0
7.765769f0
7.607672f0
7.6269684f0
7.6467953f0
7.370427f0
6.8622985f0
6.2388444f0
5.7800655f0
5.5152974f0
5.2422595f0
4.8453445f0
4.486223f0
4.196044f0
3.835113f0
3.4795947f0
3.3511903f0
3.3455799f0
3.072731f0
2.8683066f0
2.7917674f0
2.5229502f0
2.324939f0
2.278429f0
2.221004f0
2.004831f0
1.8743603f0
1.7792071f0
1.6259376f0
1.5214485f0
1.4942303f0
1.4095685f0
1.3193207f0
1.3140697f0
1.1967006f0
1.1696962f0
1.1740615f0
1.1118572f0
1.0744832f0
1.0765561f0
1.0176857f0
0.98759204f0
0.975724f0
0.941341f0
0.9185606f0
0.9031207f0
0.87351936f0
0.8610703f0
0.8372199f0
0.8144988f0
0.80590844f0
0.79650027f0
0.775024f0
0.76130676f0
0.74655825f0
0.7355968f0
0.72696066f0
0.71280533f0
0.70455706f0
0.69575185f0
0.68054414f0
0.6738972f0
0.661952f0
0.64079183f0
0.63365126f0
0.6316536f0
0.6187668f0
0.6073364f0
0.598527f0
0.59384036f0
0.5776457f0
0.57077163f0
0.5592388f0
0.5536417f0
0.54242903f0
0.53512037f0
0.5229605f0
0.5107052f0
0.5048552f0
0.50145507f0
0.4896844f0
0.48140675f0
0.480699f0
0.47929642f0
0.45847002f0
0.46191406f0
0.45478743f0
0.44687825f0
0.44435424f0
0.43389216f0
0.4264202f0
0.4311778f0
0.42134514f0
0.42020157f0
0.4173627f0
0.4103177f0
0.40506166f0
0.39764664f0
0.39517745f0
0.3870261f0
0.41754454f0
0.38469657f0
0.385521f0
0.36895466f0
0.39901072f0
0.36415306f0
0.38427f0
0.35775962f0
0.36163756f0
0.35972714f0
0.35390502f0
0.3500272f0
0.34131098f0
0.3394096f0
0.3269195f0
0.32696372f0
0.32632366f0
0.3238185f0
0.3170924f0
0.3144706f0
0.30897048f0
0.30718285f0
0.30550218f0
0.3027647f0
0.29943153f0
0.30405f0
0.29471704f0
0.30424735f0
0.28541216f0
0.29260954f0
0.27749825f0
0.28257158f0
0.27483138f0
0.2790464f0
0.26756135f0
0.2706206f0
0.26644424f0
0.26261294f0
0.26586676f0
0.25474378f0
0.25791147f0
0.2497764f0
0.2574952f0
0.24729641f0
0.24811983f0
0.24009071f0
0.23987657f0
0.23490126f0
0.24069345f0
0.25086594f0
0.22898777f0
0.24652985f0
0.23221287f0
0.23447825f0
0.22969405f0
0.2212926f0
0.22186337f0
0.2164483f0
0.22427739f0
0.20793493f0
0.21218304f0
0.20951119f0
0.20175019f0
0.19838017f0
0.19745214f0
0.19621529f0
0.19241141f0
0.21161525f0
0.25557f0
0.18895179f0
0.2435294f0
0.20411584f0
0.2524028f0
0.29656f0
0.18633014f0
0.215265f0
0.18581265f0
0.1924483f0
0.19127086f0
0.17840566f0
0.19527231f0
0.16891907f0
0.18051648f0
0.17058872f0
0.1671857f0
0.16585454f0
0.16377984f0
0.16005097f0
0.15824533f0
0.16395198f0
0.15604503f0
0.15729798f0
0.16160733f0
0.15028924f0
0.15690432f0
0.1621257f0
0.14980182f0
0.1466417f0
0.1539886f0
0.14034945f0
0.14575773f0
0.14465994f0
0.13794966f0
0.15377057f0
0.13821289f0
0.14237553f0
0.14286007f0
0.13095479f0
0.13970621f0
0.12736107f0
0.15027829f0
0.15482713f0
0.12563649f0
0.15814339f0
0.13702156f0
0.13042614f0
0.17101468f0
0.15601625f0
0.11934795f0
0.15560609f0
0.14507985f0
0.11693796f0
0.15404268f0
0.14618649f0
0.11235518f0
0.1226336f0
0.12783214f0
0.11639245f0
0.107908085f0
0.10798165f0
0.1079992f0
0.106077306f0
0.10409868f0
0.10743631f0
0.111156605f0
0.10197115f0
0.10395191f0
0.10549873f0
0.106513485f0
0.102008395f0
0.09701146f0
0.09797839f0
0.09688383f0
0.09418061f0
0.10002111f0
0.11701824f0
0.093735024f0
0.14712878f0
0.2728346f0
0.13345115f0
0.12775737f0
0.3203704f0
0.093735024f0
u: 250-element Vector{Float32}:
 0.22994581
 ⋮
```

**Comment by Abhishek-1Bhatt** [comment]
For the same code:

``julia
using OrdinaryDiffEq, DiffEqSensitivity, SimpleChains, Optimization, OptimizationFlux#, Plots

u0 = Float32[2.0, 0.0]
datasize = 30
tspan = (0.0f0, 1.5f0)
tsteps = range(tspan[1], tspan[2], length = datasize)

function trueODE!(du, u, p, t)
    true_A = [-0.1 2.0; -2.0 -0.1]
    du .= ((u.^3)'true_A)'
end

prob = ODEProblem(trueODE!, u0, tspan)
data = Array(solve(prob, Tsit5(), saveat = tsteps))

sc = SimpleChain(
                static(2),
                Activation(x -> x.^3),
                TurboDense{true}(tanh, static(50)),
                TurboDense{false}(identity, static(2))
            )
p_nn = SimpleChains.init_params(sc)

f(u,p,t) = sc(u,p)

prob_nn = ODEProblem(f, u0, tspan, p_nn)

function predict_neuralode(p)
    Array(solve(prob_nn, Tsit5();p=p,saveat=tsteps,sensealg=QuadratureAdjoint()))
end

function loss_neuralode(p)
    pred = predict_neuralode(p)
    loss = sum(abs2, data .- pred)
    return loss, pred
end

callback = function (p, l, pred; doplot = true)
    display(l)
    # plt = scatter(tsteps, data[1,:],label="data")
    # scatter!(plt, tsteps, pred[1,:], label = "prediction")
    # if doplot
    #     display(plot(plt))
    # end
    return false
end

optf = Optimization.OptimizationFunction((x,p)->loss_neuralode(x), Optimization.AutoZygote())
optprob = Optimization.OptimizationProblem(optf, p_nn)

res = Optimization.solve(optprob, ADAM(0.05),callback=callback,maxiters=300)
```

**Comment by ChrisRackauckas** [comment]
That's just a property of having a high learning rate in ADAM, if the gradients are correct. Double check that there's no aliasing issue causing incorrect gradients in training.

How is the performance of that compared to the Flux case?

**Comment by Abhishek-1Bhatt** [comment]
Yeah, but there's a better fit when we make SimpleChains output a vector by indexing(the second series of losses) for the same code

**Comment by ChrisRackauckas** [comment]
Indexing would allocate a slice. This to me is pointing to some issue with aliasing the vector and mutating it somewhere else, which is why I said the gradient should get checked.

**Comment by chriselrod** [comment]
Is something like this happening?
```julia
x = vjp!(sc)
y = vjp!(sc)
# use x
```
?
If so, with `vec`, then `x === y`, meaning the values of `x` got overwritten by the second `vjp!` call before `x` was used.

**Comment by Abhishek-1Bhatt** [comment]
So, I tried to test for this:
```julia
using SimpleChains
using Zygote

chain = SimpleChain(
    (static(5)),
    TurboDense(SimpleChains.relu, static(5)),
    TurboDense(SimpleChains.relu, static(5)),
    TurboDense(identity, static(5))
)

ps = SimpleChains.init_params(chain)

xs = randn(5)
ys = rand(5)
ys ./= sum(ys)

loss(ps) = sum(abs2, ys .- Array(chain(xs, ps)))

a = Zygote.gradient(loss, ps)
b = Zygote.gradient(loss, ps)
```
and on comparing a and b
```julia
julia> a == b
true

julia> a === b
true
```
I guess this confirms we have aliasing somewhere?

**Comment by ChrisRackauckas** [comment]
Well the two gradient vectors are exactly the same pointer. That's not necessarily bad, it does mean though that if you calculate another gradient it invalidates your previous gradient vector, so one has to be very careful with this (any nice way to throw an error/warning would be good).

**Comment by chriselrod** [comment]
> I guess this confirms we have aliasing somewhere?

Yes, that is intentional.

**Comment by ChrisRackauckas** [comment]
>Is something like this happening?

It only requires one vjp per `f` update, and then the caches are overwritten anyways. So it should be fine in the neural ODE context. This is the function to investigate:

https://github.com/SciML/DiffEqSensitivity.jl/blob/master/src/derivative_wrappers.jl#L422-L461

**Comment by ChrisRackauckas** [comment]
Test https://github.com/SciML/DiffEqSensitivity.jl/pull/638 on this to see if it solves it. I think the issue is that `dy` is aliased to a value that is then used in the derivative calculation, so we just need to broadcast out its values before triggering the pullback.

If this works, we should definitely make sure to put an integration test on this in DiffEqSensitivity.jl

**Comment by Abhishek-1Bhatt** [comment]
Looks better than before
[losses.txt](https://github.com/PumasAI/SimpleChains.jl/files/8935433/losses.txt)

**Comment by ChrisRackauckas** [comment]
Can you put together a gradient and fit integration test for DiffEqSensitivity?

**Comment by chriselrod** [comment]
> Looks better than before
> [losses.txt](https://github.com/PumasAI/SimpleChains.jl/files/8935433/losses.txt)

Those still look bad vs "when indexing" above?

**Comment by Abhishek-1Bhatt** [comment]
[losses.txt](https://github.com/PumasAI/SimpleChains.jl/files/8935862/losses.txt)
Yeah, I was re running it for tests right now, and sometimes its even worse, it looks like https://github.com/SciML/DiffEqSensitivity.jl/pull/638 wasn't quite it

**Comment by Abhishek-1Bhatt** [comment]
[losses.txt](https://github.com/PumasAI/SimpleChains.jl/files/8935915/losses.txt)
It gets to a minima but the oscillations are huge

**Comment by chriselrod** [comment]
> [losses.txt](https://github.com/PumasAI/SimpleChains.jl/files/8935915/losses.txt)
> It gets to a minima but the oscillations are huge, so the gradient accuracy is still questionable

If it stops oscillating when you create a copy, then that suggests the gradients are fine, and the problem is that there is still some sort of corruption going on due to uses of a returned vector after repeated calls.

**Comment by chriselrod** [comment]
In other words,
```julia
julia> a == b
true

julia> a === b
true
```
this is an intentional part of how SimpleChains is written, to save memory.
That means it is the responsibility of libraries using it to make sure that this is okay.

If it is too difficult, I am open to having an easy to use and safe high level API, as long as there is still a low level API enabling optimal performance.
That is, I am open to having `ChainRules.rrule` result in copies.

I already conceded and am using `task_local_storage` for memory to avoid thread-safety issues.

**Comment by ChrisRackauckas** [comment]
It doesn't need to. We just need to figure out what the actual issue is, fix it, and put good tests on it. The purpose of SimpleChains is to be fast, and I would just recommend testing the gradients against Flux first, the flipping to SimpleChains. That should be the proposed workflow.

**Comment by chriselrod** [comment]
Yeah, that's why we also added Flux support to DeepPumas.

**Comment by chriselrod** [comment]
Closing in favor of #92

**Pull request closed without merging**
