### PR TITLE
Custom loss docs fix

### PR DESCRIPTION
**Pull request by chriselrod**
We should add doc tests.

### CODE REVIEW

**Review by andreuvall — APPROVED** [review]

**Review by andreuvall — COMMENTED** [review]
I approved too quickly... I copy/pasted the `custom_loss_layer.md` example to a Julia script and tried to execute it. The last line

```julia
SimpleChains.train_unbatched!(gradients, parameters, model_loss, X, SimpleChains.ADAM(), 1:epochs);
```
fails with 

```
ERROR: MethodError: no method matching (::BinaryLogitCrossEntropyLoss{Bool, Vector{Bool}})(::Int64)
Closest candidates are:
  (::BinaryLogitCrossEntropyLoss)(::AbstractArray) at ~/.../custom_loss_layer.jl:9
  (::BinaryLogitCrossEntropyLoss)(::AbstractArray{T}, ::Ptr, ::Any) where T at ~/.../custom_loss_layer.jl:21
Stacktrace:
...
```

I am not there yet to understand the error message well. I tried playing around with the type of `Y`, the type of the elements in `Y`, and the shape of `Y`, but this didn't fix it.

**Review by andreuvall — APPROVED** [review]

**Comment by chriselrod** [comment]
> I approved too quickly... I copy/pasted the `custom_loss_layer.md` example to a Julia script and tried to execute it. The last line
> 
> ```julia
> SimpleChains.train_unbatched!(gradients, parameters, model_loss, X, SimpleChains.ADAM(), 1:epochs);
> ```
> 
> fails with
> 
> ```
> ERROR: MethodError: no method matching (::BinaryLogitCrossEntropyLoss{Bool, Vector{Bool}})(::Int64)
> Closest candidates are:
>   (::BinaryLogitCrossEntropyLoss)(::AbstractArray) at ~/.../custom_loss_layer.jl:9
>   (::BinaryLogitCrossEntropyLoss)(::AbstractArray{T}, ::Ptr, ::Any) where T at ~/.../custom_loss_layer.jl:21
> Stacktrace:
> ...
> ```
> 
> I am not there yet to understand the error message well. I tried playing around with the type of `Y`, the type of the elements in `Y`, and the shape of `Y`, but this didn't fix it.

**Comment by chriselrod** [comment]
Mind showing me the script? Are you sure you copy pasted from the updated version here?
It should have fixed that particular error.

**Comment by chriselrod** [comment]
Sorry, it should be `epochs` and not `1:epoch`s.
```julia
julia> @time using SimpleChains
  1.854893 seconds (5.14 M allocations: 355.604 MiB, 5.08% gc time, 5.56% compilation time)

julia> struct BinaryLogitCrossEntropyLoss{T,Y<:AbstractVector{T}} <: SimpleChains.AbstractLoss{T}
           targets::Y
       end

julia> SimpleChains.target(loss::BinaryLogitCrossEntropyLoss) = loss.targets

julia> (loss::BinaryLogitCrossEntropyLoss)(x::AbstractArray) = BinaryLogitCrossEntropyLoss(x)

julia> function calculate_loss(loss::BinaryLogitCrossEntropyLoss, logits)
           y = loss.targets
           total_loss = zero(eltype(logits))
           for i in eachindex(y)
               p_i = inv(1 + exp(-logits[i]))
               y_i = y[i]
               total_loss -= y_i * log(p_i) + (1 - y_i) * (1 - log(p_i))
           end
           total_loss
       end
calculate_loss (generic function with 1 method)

julia> function (loss::BinaryLogitCrossEntropyLoss)(previous_layer_output::AbstractArray{T}, p::Ptr, pu) where {T}
           total_loss = calculate_loss(loss, previous_layer_output)
           total_loss, p, pu
       end

julia> function SimpleChains.layer_output_size(::Val{T}, sl::BinaryLogitCrossEntropyLoss, s::Tuple) where {T}
           SimpleChains._layer_output_size_no_temp(Val{T}(), sl, s)
       end

julia> function SimpleChains.forward_layer_output_size(::Val{T}, sl::BinaryLogitCrossEntropyLoss, s) where {T}
           SimpleChains._layer_output_size_no_temp(Val{T}(), sl, s)
       end

julia> function SimpleChains.chain_valgrad!(
           __,
           previous_layer_output::AbstractArray{T},
           layers::Tuple{BinaryLogitCrossEntropyLoss},
           _::Ptr,
           pu::Ptr{UInt8},
       ) where {T}
           loss = getfield(layers, 1)
           total_loss = calculate_loss(loss, previous_layer_output)
           y = loss.targets
       
           # Store the backpropagated gradient in the previous_layer_output array.
           for i in eachindex(y)
               sign_arg = 2 * y[i] - 1
               # Get the value of the last logit
               logit_i = previous_layer_output[i]
               previous_layer_output[i] = -(sign_arg * inv(1 + exp(sign_arg * logit_i)))
           end
       
           return total_loss, previous_layer_output, pu
       end

julia> model = SimpleChain(
           static(2),
           TurboDense(tanh, 32),
           TurboDense(tanh, 16),
           TurboDense(identity, 1)
       )
SimpleChain with the following layers:
TurboDense static(32) with bias.
Activation layer applying: tanh
TurboDense static(16) with bias.
Activation layer applying: tanh
TurboDense static(1) with bias.

julia> batch_size = 64
64

julia> X = rand(Float32, 2, batch_size);

julia> Y = rand(Bool, batch_size);

julia> parameters = SimpleChains.init_params(model);

julia> gradients = SimpleChains.alloc_threaded_grad(model);

julia> # Add the loss like any other loss type
       model_loss = SimpleChains.add_loss(model, BinaryLogitCrossEntropyLoss(Y));

julia> @time SimpleChains.valgrad!(gradients, model_loss, X, parameters);
  5.311685 seconds (9.25 M allocations: 603.990 MiB, 5.38% gc time, 100.00% compilation time)

julia> epochs = 100
100

julia> @time SimpleChains.train_unbatched!(gradients, parameters, model_loss, X, SimpleChains.ADAM(), epochs);
  1.241317 seconds (2.33 M allocations: 151.688 MiB, 5.61% gc time, 114.15% compilation time)

julia> @time SimpleChains.train_unbatched!(gradients, parameters, model_loss, X, SimpleChains.ADAM(), epochs);
  0.000537 seconds
```

**Comment by andreuvall** [comment]
For me, it fails now with the error below. It must be noted though that I could not try running the code with the latest `StrideArraysCore` (0.4.7).

```
ERROR: ArgumentError: sizeof(Float32) == 4, but stride between vector loads is given as 0, which is not a positive integer multiple.
Stacktrace:
  [1] vload_quote_llvmcall_core(T_sym::Symbol, I_sym::Symbol, ind_type::Symbol, W::Int64, X::Int64, M::Int64, O::Int64, mask::Bool, align::Bool, rs::Int64)
    @ VectorizationBase ~/.julia/packages/VectorizationBase/G9NJI/src/llvm_intrin/memory_addr.jl:788
  [2] vload_quote_llvmcall(T_sym::Symbol, I_sym::Symbol, ind_type::Symbol, W::Int64, X::Int64, M::Int64, O::Int64, mask::Bool, align::Bool, rs::Int64, ret::Expr)
...
```

**Comment by chriselrod** [comment]
I tested on both Zen3 and SkylakeX using the latest release versions
```julia
(simplechains) pkg> st -m SimpleChains StrideArraysCore LoopVectorization VectorizationBase
Status `~/Documents/progwork/julia/env/simplechains/Manifest.toml`
  [bdcacae8] LoopVectorization v0.12.150
  [de6bee2f] SimpleChains v0.4.2
  [7792a7ef] StrideArraysCore v0.4.7
  [3d5dd08c] VectorizationBase v0.21.58
```
and haven't been able to reproduce that error.

**Review by andreuvall — APPROVED** [review]
The example works fine. The problem was on my side, namely, the Julia environment that I used to test the example didn't have the right `StrideArraysCore` version. With the correct version, the example runs well.

**Pull request merged**
