### PR TITLE
`alloc_return` needs 5 args

### PR DESCRIPTION
**Pull request by chriselrod**

### CODE REVIEW

**Comment by mohamed82008** [comment]
Needs a test?

**Comment by chriselrod** [comment]
> Needs a test?

I'm hoping @lcontento can provide one.

**Comment by lcontento** [comment]
> > Needs a test?
> 
> I'm hoping @lcontento can provide one.

MWE:
```julia
using SimpleChains
x = randn(3, 100)
y = randn(4, 100)
chain = SimpleChain(
  static(3),
  TurboDense{true}(tanh, 8),
  TurboDense{true}(identity, 4),
)
opt = SimpleChains.ADAM()
penalty = L2Penalty(0.1)
loss = SquaredLoss
model = penalty(SimpleChains.add_loss(chain, loss(y)))
p = SimpleChains.init_params(chain)
SimpleChains.train_batched!(copy(p), p, model, x, opt, 10)
```

**Comment by chriselrod** [comment]
Thanks. That segfaulted for me, so this PR needs work.

**Comment by chriselrod** [comment]
Added a test. Is this good to go @mohamed82008 ?

**Review by mohamed82008 — APPROVED** [review]
Looks good to me. Thank Chris.

**Pull request merged**
