### PR TITLE
apply mean to full batch, not chunked pieces when threading

### PR DESCRIPTION
**Pull request by chriselrod**
Number of threads should not influence training.

### CODE REVIEW

**Comment by korsbo** [comment]
From our meeting, I take it that there are some design decisions to be made in here. That's not immediately apparent from just reading the code diff. Could you outline the crossroads that we're currently at?

**Comment by chriselrod** [comment]
> From our meeting, I take it that there are some design decisions to be made in here. That's not immediately apparent from just reading the code diff. Could you outline the crossroads that we're currently at?

https://github.com/PumasAI/SimpleChains.jl/issues/56

I should probably just implement all of them, perhaps as separate functions so we don't even need a default.
(The implementations would of course reuse code).

**Comment by chriselrod** [comment]
This still fixes an issue, so I think it's a good idea to get this in.

**Review by korsbo — CHANGES_REQUESTED** [review]
Looks good to me apart from some comment linting.

**Comment by korsbo** [comment]
ping me on slack when you've looked over the linting and I'll hit the approve button.

**Comment by chriselrod** [comment]
For the life of me, I can't get tests to fail locally, and can't get them to pass on CI.

**Comment by andreasnoack** [comment]
Could it be architecture specific? You don't hit BLAS here, right? Could you try to target the same architecture as used by CI?

**Comment by chriselrod** [comment]
> Could it be architecture specific? You don't hit BLAS here, right? Could you try to target the same architecture as used by CI?

No BLAS.
I believe some of the errors are new and specific to Julia master, so I'm rebuilding the latest Julia master to see if I can at least reproduce those.

But the `@test all(isfinite, p)` and `@test all(isfinite, G)` tests still failing suggests some reading of out of bounds memory.

I'm now testing without `@turbo` which should hopefully reduce the chance of architecture specific problems coming into play, and also enable bounds errors.

Seems to have found something!
Maybe I should come up with a way to allow testing without `@turbo`.

**Comment by chriselrod** [comment]
Hmm. Times out without `@turbo`, but doesn't seem to hit a bounds error in the 6 hours it did run before timing out.

**Review by korsbo — APPROVED** [review]

**Pull request merged**
